apiVersion: apps/v1
kind: Deployment
metadata:
  name: sf-deployment
spec:
  selector:
    matchLabels:
      app: sf-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sf-app
    spec:
      containers:
        - name: "app"
          image: "registry.gitlab.com/m4fm4n/stage-2:latest"
          command: ["sh", "-c", "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:3003"]
          env:
            - name: DB_HOST
              value: localhost
            - name: DB_NAME
              value: tutorial-dev
            - name: DB_USER
              value: USER
            - name: DB_PASS
              value: password
          ports:
            - containerPort: 3003

        - name: "db"
          image: "postgres:13-alpine"
          env:
            - name: POSTGRES_DB
              value: tutorial-dev
            - name: POSTGRES_USER
              value: USER
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: "db-pv"
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: "db-pv"
          persistentVolumeClaim:
            claimName: "pvc"
